// Auto-generated by Supabase CLI — do not edit manually
// Regenerate: npm run db:types (requires SUPABASE_ACCESS_TOKEN in env)
/* eslint-disable @typescript-eslint/consistent-type-definitions, @typescript-eslint/consistent-indexed-object-style */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      admin_users: {
        Row: {
          created_at: string
          email: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          email?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          email?: string | null
          user_id?: string
        }
        Relationships: []
      }
      analytics_events: {
        Row: {
          created_at: string
          entity_id: string | null
          entity_slug: string | null
          entity_type: string | null
          event_type: string
          id: number
          metadata: Json | null
        }
        Insert: {
          created_at?: string
          entity_id?: string | null
          entity_slug?: string | null
          entity_type?: string | null
          event_type: string
          id?: never
          metadata?: Json | null
        }
        Update: {
          created_at?: string
          entity_id?: string | null
          entity_slug?: string | null
          entity_type?: string | null
          event_type?: string
          id?: never
          metadata?: Json | null
        }
        Relationships: []
      }
      categories: {
        Row: {
          created_at: string
          description: string
          display_order: number
          id: string
          image_url: string | null
          is_active: boolean
          is_featured: boolean
          name: string
          occasion: string | null
          slug: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description: string
          display_order?: number
          id?: string
          image_url?: string | null
          is_active?: boolean
          is_featured?: boolean
          name: string
          occasion?: string | null
          slug: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string
          display_order?: number
          id?: string
          image_url?: string | null
          is_active?: boolean
          is_featured?: boolean
          name?: string
          occasion?: string | null
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      complaints: {
        Row: {
          claimed_amount: number | null
          complaint_type: string
          consumer_address: string
          consumer_doc_number: string
          consumer_doc_type: string
          consumer_email: string
          consumer_name: string
          consumer_phone: string | null
          consumer_request: string
          correlativo: number
          created_at: string
          detail: string
          email_sent: boolean
          guardian_name: string | null
          id: string
          is_minor: boolean
          item_description: string
          item_type: string
          provider_response: string | null
          responded_at: string | null
          status: string
          updated_at: string
        }
        Insert: {
          claimed_amount?: number | null
          complaint_type: string
          consumer_address: string
          consumer_doc_number: string
          consumer_doc_type: string
          consumer_email: string
          consumer_name: string
          consumer_phone?: string | null
          consumer_request: string
          correlativo?: never
          created_at?: string
          detail: string
          email_sent?: boolean
          guardian_name?: string | null
          id?: string
          is_minor?: boolean
          item_description: string
          item_type: string
          provider_response?: string | null
          responded_at?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          claimed_amount?: number | null
          complaint_type?: string
          consumer_address?: string
          consumer_doc_number?: string
          consumer_doc_type?: string
          consumer_email?: string
          consumer_name?: string
          consumer_phone?: string | null
          consumer_request?: string
          correlativo?: never
          created_at?: string
          detail?: string
          email_sent?: boolean
          guardian_name?: string | null
          id?: string
          is_minor?: boolean
          item_description?: string
          item_type?: string
          provider_response?: string | null
          responded_at?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      flower_types: {
        Row: {
          created_at: string
          display_order: number
          id: string
          name: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_order?: number
          id?: string
          name: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_order?: number
          id?: string
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      product_color_assignments: {
        Row: {
          color_id: string
          created_at: string
          product_id: string
        }
        Insert: {
          color_id: string
          created_at?: string
          product_id: string
        }
        Update: {
          color_id?: string
          created_at?: string
          product_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_color_assignments_color_id_fkey"
            columns: ["color_id"]
            isOneToOne: false
            referencedRelation: "product_colors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_color_assignments_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      product_colors: {
        Row: {
          created_at: string
          display_order: number
          hex: string | null
          id: string
          label: string
          name: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_order?: number
          hex?: string | null
          id?: string
          label: string
          name: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_order?: number
          hex?: string | null
          id?: string
          label?: string
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      product_flower_type_assignments: {
        Row: {
          created_at: string
          flower_type_id: string
          product_id: string
        }
        Insert: {
          created_at?: string
          flower_type_id: string
          product_id: string
        }
        Update: {
          created_at?: string
          flower_type_id?: string
          product_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_flower_type_assignments_flower_type_id_fkey"
            columns: ["flower_type_id"]
            isOneToOne: false
            referencedRelation: "flower_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_flower_type_assignments_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      product_images: {
        Row: {
          alt_text: string | null
          created_at: string
          display_order: number
          id: string
          is_primary: boolean
          product_id: string
          updated_at: string
          url: string
        }
        Insert: {
          alt_text?: string | null
          created_at?: string
          display_order?: number
          id?: string
          is_primary?: boolean
          product_id: string
          updated_at?: string
          url: string
        }
        Update: {
          alt_text?: string | null
          created_at?: string
          display_order?: number
          id?: string
          is_primary?: boolean
          product_id?: string
          updated_at?: string
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_images_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          category_id: string
          colors: string[]
          created_at: string
          description: string
          display_order: number
          flower_types: string[]
          id: string
          image_url: string
          images: string[]
          includes: Json
          is_active: boolean
          is_featured: boolean
          name: string
          note: string | null
          occasion: string | null
          price: number
          price_variants: Json | null
          search_vector: unknown
          slug: string
          updated_at: string
        }
        Insert: {
          category_id: string
          colors?: string[]
          created_at?: string
          description: string
          display_order?: number
          flower_types?: string[]
          id?: string
          image_url: string
          images?: string[]
          includes?: Json
          is_active?: boolean
          is_featured?: boolean
          name: string
          note?: string | null
          occasion?: string | null
          price: number
          price_variants?: Json | null
          search_vector?: unknown
          slug: string
          updated_at?: string
        }
        Update: {
          category_id?: string
          colors?: string[]
          created_at?: string
          description?: string
          display_order?: number
          flower_types?: string[]
          id?: string
          image_url?: string
          images?: string[]
          includes?: Json
          is_active?: boolean
          is_featured?: boolean
          name?: string
          note?: string | null
          occasion?: string | null
          price?: number
          price_variants?: Json | null
          search_vector?: unknown
          slug?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "category_price_summary"
            referencedColumns: ["category_id"]
          },
        ]
      }
    }
    Views: {
      category_price_summary: {
        Row: {
          category_id: string | null
          price_from: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      create_complaint: {
        Args: {
          p_claimed_amount?: number
          p_complaint_type: string
          p_consumer_address: string
          p_consumer_doc_number: string
          p_consumer_doc_type: string
          p_consumer_email: string
          p_consumer_name: string
          p_consumer_phone?: string
          p_consumer_request: string
          p_detail: string
          p_guardian_name?: string
          p_is_minor?: boolean
          p_item_description: string
          p_item_type: string
        }
        Returns: {
          correlativo: number
          created_at: string
          id: string
        }[]
      }
      delete_category_cascade: {
        Args: { p_category_id: string }
        Returns: string[]
      }
      delete_category_reassign: {
        Args: { p_category_id: string; p_reassign_to: string }
        Returns: string
      }
      delete_flower_type: { Args: { p_name: string }; Returns: undefined }
      delete_product_color: { Args: { p_name: string }; Returns: undefined }
      get_active_category_ids: {
        Args: never
        Returns: {
          category_id: string
        }[]
      }
      get_color_distribution: {
        Args: never
        Returns: {
          color_name: string
          count: number
        }[]
      }
      get_daily_event_counts: {
        Args: { p_since: string }
        Returns: {
          count: number
          date: string
          event_type: string
        }[]
      }
      get_event_type_counts: {
        Args: { p_since: string; p_until?: string }
        Returns: {
          count: number
          event_type: string
          source: string
        }[]
      }
      get_flower_type_distribution: {
        Args: never
        Returns: {
          count: number
          flower_type: string
        }[]
      }
      get_flower_type_usage: {
        Args: { p_name: string }
        Returns: {
          product_id: string
          product_name: string
        }[]
      }
      get_inventory_status: {
        Args: never
        Returns: {
          active: number
          featured: number
          inactive: number
          total: number
        }[]
      }
      get_price_distribution: {
        Args: never
        Returns: {
          count: number
          range: string
        }[]
      }
      get_price_range_by_category: {
        Args: never
        Returns: {
          avg_price: number
          category: string
          max_price: number
          min_price: number
        }[]
      }
      get_product_color_usage: {
        Args: { p_name: string }
        Returns: {
          product_id: string
          product_name: string
        }[]
      }
      get_product_conversion_metrics: {
        Args: { p_since: string }
        Returns: {
          entity_slug: string
          views: number
          whatsapp_clicks: number
        }[]
      }
      get_product_ids_with_views: {
        Args: { p_since: string }
        Returns: {
          entity_id: string
        }[]
      }
      get_products_per_category: {
        Args: never
        Returns: {
          active: number
          category: string
          count: number
        }[]
      }
      get_top_entities: {
        Args: { p_event_type: string; p_limit?: number; p_since: string }
        Returns: {
          count: number
          entity_slug: string
        }[]
      }
      get_whatsapp_source_counts: {
        Args: { p_since: string }
        Returns: {
          count: number
          source: string
        }[]
      }
      is_admin: { Args: { p_user_id?: string }; Returns: boolean }
      rename_flower_type: {
        Args: { p_new_name: string; p_old_name: string }
        Returns: undefined
      }
      rename_product_color: {
        Args: { p_new_name: string; p_old_name: string }
        Returns: undefined
      }
      reorder_categories: {
        Args: { p_ordered_ids: string[] }
        Returns: undefined
      }
      reorder_products: {
        Args: { p_ordered_ids: string[] }
        Returns: undefined
      }
      require_admin: { Args: never; Returns: undefined }
      set_product_taxonomy: {
        Args: {
          p_color_ids: string[]
          p_flower_ids: string[]
          p_images: Json
          p_product_id: string
        }
        Returns: undefined
      }
      unaccent: { Args: { "": string }; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
